.TH sqtd "1" "09.09.2013" "sqtc" "Пользовательские команды"
.SH ИМЯ
sqtd \- Squid traffic quotation client 
.SH СИНТАКСИС
sqtc [-i] [-h] [-l] [-s файл] 
.SH ОПИСАНИЕ
.B sqtc
предназначен для ограничения интернет траффика пользователя на основе запросов к программе sqtd через файл сокета. Для запуска демона необходимо указать расположение  файла сокета (параметр -s командной строки, параметр SockFile конфигурационного файла sqtd). Клиент может работать в интерактивном (параметр -i) и неинтерактивном режиме. Список команд интерактивного режима можно получить при помощи команды "help". Команда "config" получает от демона sqtd информацию о текущей конфигурации. Kоманды "limits" и "traf" выводят в консоль информацию об установленных лимитах. Команда user отображает OK если доступ в интернет пользователю разрешен и ERR, если доступ закрыт. В неинтерактивном режиме программа принимает на стандартный ввод имя пользователя и выводит на стандартный вывод OK или ERR. В неинтерактивном режиме программа быть использована для построения внешних списков доступа squid. Для этого в файле конфигурации squid необходимо указать следующее
external_acl_type name  %LOGIN  /path/to/sqtc -s /path/to/sqtd.sock.file. При ошибке доступа к файлу сокета в неитерактивном режиме программа выдает ERR если не указана опция командной строки -l или OK если опция указана.

.SH КЛЮЧИ
.TP
\fB\-s файл\fR  
файл сокета
.TP
\fB\-h\fR
вывод краткой  справки
.TP
\fB\-i\fR
запуск в интерактивном режиме

.SH ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ
.TP
0 \- нормальное завершение работы
.TP
1 \- небольшие проблемы
.TP
2 \- серьёзная проблема
.SH ФАЙЛЫ
.I /var/lib/sqtd/sqtd.sock  
.RS
файл сокета 
.RE

.SH АВТОРЫ
Программа разработана Вершининым Владимиром Ивановичем 
<vershininvi@rambler.ru>. Россия. Волгоград.
.SH "СМОТРИТЕ ТАКЖЕ"
man getent, man smb.conf, man squid, man sqtd.
