.TH sqtc "1" "09.09.2013" "sqtc" "Пользовательские команды"
.SH ИМЯ
sqtc \- Squid traffic quotation client 
.SH СИНТАКСИС
sqtc [-i] [-h] [-l] [-s файл] 
.SH ОПИСАНИЕ
.B sqtc
предназначен для ограничения интернет траффика пользователя на основе запросов к программе sqtd через файл сокета. Для запуска демона необходимо указать расположение  файла сокета (параметр -s командной строки, параметр SockFile конфигурационного файла sqtd, по умолчанию /var/lib/sqtd/sqtd.sock). Клиент может работать в интерактивном (параметр -i) и неинтерактивном режиме. 

.SH Интерактивный режим
.TP
\fB help\fR 
Выводит список команд интерактивного режима. 
.TP
\fB config\fR
gолучает от демона sqtd информацию о текущей конфигурации. 
.TP
\fB limits\fR
выводит в консоль информацию об установленных лимитах, если имя пользователя не указано - выводится информация обо всех пользователях. 
.TP
\fB traf\fR
выводит в консоль информацию о траффике, если имя пользователя не указано - выводится информация обо всех пользователях. 

.TP
\fB user\fR
отображает OK если доступ в интернет пользователю разрешен и ERR, если доступ закрыт.


.SH Неинтерактивный режим
В неинтерактивном режиме программа принимает на стандартный ввод имя пользователя (url encoded) и выводит на стандартный вывод OK или ERR. В неинтерактивном режиме программа быть использована для построения внешних списков доступа squid. 

Для этого в файле конфигурации squid необходимо указать следующее:
external_acl_type name  %LOGIN  /path/to/sqtc  
При ошибке доступа к файлу сокета  программа выдает ERR, если не указана опция командной строки -l или OK если опция указана.

.SH КЛЮЧИ
.TP
\fB\-s  файл\fR  
файл сокета
.TP
\fB\-h\fR
вывод краткой  справки
.TP
\fB\-i\fR
запуск в интерактивном режиме

.SH ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ
.TP
0 \- нормальное завершение работы
.TP
1 \- небольшие проблемы
.TP
2 \- серьёзная проблема
.SH ФАЙЛЫ
.I /var/lib/sqtd/sqtd.sock  
.RS
файл сокета 
.RE

.SH АВТОРЫ
Программа разработана Вершининым Владимиром Ивановичем 
<vershininvi@rambler.ru>. Россия. Волгоград.
.SH "СМОТРИТЕ ТАКЖЕ"
man getent, man smb.conf, man squid, man sqtd.
