.TH sqtd "1" "09.09.2013" "sqtd" "Пользовательские команды"
.SH ИМЯ
sqtd \- Squid traffic quotation daemon 
.SH СИНТАКСИС
sqtd [-c файл] [-n] [-v] [-h]
.SH ОПИСАНИЕ
.B sqtd
ограничивает интернет траффика пользователя на основе квот, установленных в файле конфигурации. По умолчанию файла конфигурации расположен в /etc/sqtd/sqtd.conf (может быть изменено опцией командной строки  -с ). Анализ файла журнала доступа squid (acces.log)  производится периодически, с интервалом указанным при помощи ключа конфигурационного файла CheckInterval (в секундах). Журнал работы sqtd записывается в файле, указанный при помощи ключа конфигурационного файла LogFile, либо в системный журнал (по умолчанию), либо на стандартный вывод, если при запуске указана опция командной строки -n. Идентификатор процесса записывается в файл, указанный при помощи ключа  PidFile файла конфигурации. Sqtd ожидает подключение клиентов к файлу сокета (ключа SocksFile). Для обращения к файлу сокета используется программа-клиент sqtc (man sqtc), которая может быть запущена в интерактивном режиме, либо исползована для организации внешних списков доступа в файле конфигурации squid. 
.SH ОПЦИИ
.TP
\fB\-c путькфайлу\fR  
использовать файл конфигурации
.TP
\fB\-h\fR
вывод краткой справки
.TP
\fB\-v\fR
вывод версии программы
.TP
\fB\-n\fR
запуск в отладочном  режиме с выводом отладочных сообщений в консоль

.SH ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ
.TP
0 \- нормальное завершение работы
.TP
1 \- ошибка

.SH ФАЙЛЫ
.I /etc/sqtd/sqtd.conf 
.RS
файл конфигурации 
.RE
.I /var/lib/sqtd/sqtd.pid
.RS
временный файл идентификатора процесса, используется для идентификации процесса sqtd  
.RE
.I /var/lib/sqtd/sqtd.sock
.RS
временный файл сокета 
.RE

.SH ФАЙЛ КОНФИГУРАЦИ
sqtd обрабатывает файл конфигурации последовательно от начала до конца. Строки, начинающиеся с символа # являются комментариями. Пустые строки игнорируются. Каждая непустая строка файла конфигурации представляет собой пару КЛЮЧ ЗНАЧЕНИЕ. Если ЗНАЧЕНИЕ представляет собой путь к файлу - рекомендуется указывать полный путь.

.RE
\fBКлючи файла конфигурации:\fR
.TP
\fBCheckInterval число\fR  
Период проверки. По умолчанию 300 (5 минут). По истечении указанного периода производится реконфигурация сервиса и проверка новых записей в файле журнала доступа squid (access.log).   
.RE
.TP
\fBAccessLogFile файл\fR 
путь к файлу журнала доступа squid (access.log). По умолчанию /var/log/squid/access.log
.RE
.TP
\fBLogFile файл\fR       
путь к файлу лога (по умолачнию - системный лог в режиме демона и стандартный вывод в режиме отладки (опция командной строки -n))
.RE
.TP
\fBPidFile файл\fR 
путь к файлу идентификатора процесса  (по умолчанию /var/lib/sqtd/sqtd.pid)
.RE
.TP
\fBSosckFile файл\fR 
путь к файлу сокета  (по умолчанию /var/lib/sqtd/sqtd.sock). Доступ к сокету контролируется ключами конфигурации SockUser, SockDomain,SockMod. Проверка прав может быть осуществлена командой ls -lh /путь/к файлу/сокета. При использовании sqtc совместно со squid необходимо проверить под каким пользователем squid запускает sqtc (ps -aF | grep sqtc).   
.RE
.TP
\fBSosckUser username\fR 
Владелец файла сокета 
.RE
.TP
\fBSosckUser groupname\fR 
Группа файла сокета 
.RE
.TP
\fBSoskMod mode\fR 
Режим доступа к файлу сокета (770) 
.RE

.TP
\fBSystemDomainDelimiter\fR 
 Разделитель имени домена и пользователя, используемый в системе. Может быть получен командой getent passwd 
.RE

.TP
\fBSquidDomainDelimiter\fR 
Разделитель имени домена и пользователя, который используется  в файле лога доступа squid (access.log)
.RE

.TP
\fBLimit ограничение\fR
Ограничения для пользователей указываются ключевым словом Limit. В качестве значения для ключевого слова Limit используется строка ограничения вида ТИП:ИМЯ:ПЕРИОД:КОЛИЧЕСТВО. Ограничение может быть двух типов - пользовательское  (u) или групповое (g). ИМЯ определяет имя пользователя или группы, на которое распространяется действие данного ограничения. ПЕРИОД - определяет срок действия ограничения и может быть представлен одним из трех значений h (час), d(день) или m (месяц). КОЛИЧЕСТВО указывает объем разрешенного траффика в байтах, килобайтах (K), мегабайтах (M) или гигабайтах (G). Если в качестве КОЛИЧЕСТВА указан 0, то для пользователя или группы  ограничения не используются. Поскольку файл конфигурации обрабатывается последовательно от начала и до конца, на пользователя или группу будет воздействовать самое последнее применимое к нему ограничение на соответсвующий период. ИМЯ  должно соответсвовать выводу getent passwd ( getent group). 
.RE
.SH АВТОРЫ
Программа разработана Вершининым Владимиром 
<vershininvi@rambler.ru>  Россия. Волгоград.
.SH "СМОТРИТЕ ТАКЖЕ"
man getent, man smb.conf, man squid, man sqtc, man ps, man chmod, man ls, man grep.
